export type FoodCategory =
  | "veg"
  | "fruit"
  | "egg"
  | "fat"
  | "protein"
  | "carb"
  | "dairy"
  | "sauce";

export type FoodUnit = "g" | "ml" | "piece";

export type FoodPreset = {
  id: string;
  name: string;
  emoji: string;
  // Never set on the built-in presets themselves — carried here so a preset
  // merged with a user override (which can add a photo icon) keeps its type.
  iconImageDataUrl?: string;
  unit: FoodUnit;
  defaultAmount: number;
  caloriesPer: number;
  proteinPer: number;
  // New macros (per unit). Optional for forward-compat with old serialized
  // overrides; treated as 0 when missing.
  fiberPer?: number;
  carbsPer?: number;
  fatsPer?: number;
  category: FoodCategory;
  // Short citation for the macro numbers (e.g. "USDA FDC #171477"). Surfaced
  // in the food detail modal so users can sanity-check what's loaded.
  source?: string;
};

export type CustomFood = {
  id: string;
  name: string;
  emoji?: string;
  // See lib/types.ts CustomFood — small, browser-generated icon image.
  iconImageDataUrl?: string;
  unit: FoodUnit;
  defaultAmount: number;
  caloriesPer: number;
  proteinPer: number;
  fiberPer?: number;
  carbsPer?: number;
  fatsPer?: number;
  source?: string;
};

export const CATEGORY_LABEL: Record<FoodCategory, string> = {
  veg: "Veg",
  fruit: "Fruit",
  egg: "Eggs",
  fat: "Fats",
  protein: "Protein",
  carb: "Carbs",
  dairy: "Dairy",
  sauce: "Sauces",
};

// Tab order in the food picker. Protein/Carbs first (logged most), then the
// new Dairy and Sauces sections (easy to forget, calorie-dense), then
// Fruit/Veg/Fats.
export const CATEGORY_ORDER: FoodCategory[] = [
  "protein",
  "carb",
  "dairy",
  "sauce",
  "fruit",
  "veg",
  "fat",
];

// Guess the category for a typed food name so new custom foods land on the
// right tab without the user having to pick one. Order matters — the most
// specific cues (condiments, protein supplements) run before broad food
// groups, mirroring suggestEmoji in components/emoji-picker.tsx.
const CATEGORY_RULES: Array<[RegExp, FoodCategory]> = [
  [
    /ketchup|mayo|mayonnaise|aioli|mustard|chutney|salsa|dressing|vinaigrette|gravy|relish|pesto|sriracha|tabasco|hot\s*sauce|soy\s*sauce|teriyaki|bbq|barbe?cue|hummus|sauce|condiment|seasoning|\bspice\b|\bsalt\b|honey|\bjam\b|peri.?peri|piri.?piri/,
    "sauce",
  ],
  [/whey|protein\s*(shake|powder|scoop|bar)|isolate|casein/, "protein"],
  [/\begg/, "egg"],
  [
    /milk|yog(h)?urt|curd|dahi|paneer|cheese|lassi|kefir|ice\s*cream|gelato|cream\b/,
    "dairy",
  ],
  [
    /chicken|poultry|beef|steak|mutton|lamb|pork|turkey|duck|fish|salmon|tuna|mackerel|sardine|prawn|shrimp|crab|sausage|\bham\b|tofu|tempeh|seitan|soya?\s*chunk|\bdal\b|lentil|chickpea|chana|rajma|bean/,
    "protein",
  ],
  [
    /\boil\b|ghee|butter|almond|cashew|walnut|pistachio|peanut|\bnuts?\b|seed|avocado|chocolate|tahini|olive/,
    "fat",
  ],
  [
    /apple|banana|orange|mango|grape|berr(y|ies)|strawberr|melon|kiwi|peach|pear|pineapple|papaya|pomegranate|plum|cherry|lychee|guava|fruit|date\b|fig\b|raisin/,
    "fruit",
  ],
  [
    /rice|bread|roti|chapat(h)?i|naan|paratha|oats?\b|oatmeal|pasta|spaghetti|noodle|macaroni|potato|quinoa|cereal|granola|muesli|tortilla|bagel|biryani|pulao|poha|upma|idli|dosa|cracker|cookie|biscuit|cake|sugar|wrap\b|toast/,
    "carb",
  ],
  [
    /broccoli|spinach|kale|lettuce|cabbage|cauliflower|carrot|cucumber|tomato|onion|pepper|capsicum|mushroom|zucchini|courgette|beet|salad|okra|bhindi|gourd|peas?\b|veg/,
    "veg",
  ],
];

export function suggestCategory(name: string): FoodCategory | undefined {
  const n = name.trim().toLowerCase();
  if (!n) return undefined;
  for (const [re, c] of CATEGORY_RULES) if (re.test(n)) return c;
  return undefined;
}

// Best preset match for a typed food name, used to offer one-tap macro
// prefill in the custom-food dialog. Prefers an exact name, then a name that
// starts with the query (so "banana" → "Banana (medium)"), then a looser
// all-words-present match. Returns undefined when nothing is close.
export function findFoodByName(name: string): FoodPreset | undefined {
  const q = name.trim().toLowerCase();
  if (q.length < 2) return undefined;
  const tokens = q.split(/\s+/).filter(Boolean);
  let starts: FoodPreset | undefined;
  let token: FoodPreset | undefined;
  for (const p of FOOD_PRESETS) {
    const n = p.name.toLowerCase();
    if (n === q) return p;
    if (!starts && n.startsWith(q)) starts = p;
    if (!token && tokens.every((t) => n.includes(t))) token = p;
  }
  return starts ?? token;
}

// Macros per gram (or per piece for whole items). Reference numbers from
// USDA FoodData Central (FDC) and Indian Food Composition Tables (IFCT) for
// Indian-specific items. Sources are cited per-food so users can sanity-check
// the values via the food detail modal. Numbers are scaled to per-unit; UI
// rounds totals before display.

// There is no per-colour bell-pepper emoji in Unicode (🫑 only reads as
// green), so we draw a tiny bell-pepper SVG and recolour the body. Returned
// as a data URL → rendered by <FoodIcon src=…>. Computed at module load from
// code, so it never bloats stored profile JSON. Stem stays green for all.
function pepperIcon(body: string): string {
  const svg =
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">` +
    `<path d="M12 8C16.5 8 19 10.5 19 14.5C19 18 16.7 21 14.2 20.6C13.2 20.45 12.7 19.7 12 19.7C11.3 19.7 10.8 20.45 9.8 20.6C7.3 21 5 18 5 14.5C5 10.5 7.5 8 12 8Z" fill="${body}"/>` +
    `<path d="M12 8.5C12 6 12.6 4.2 15 4" fill="none" stroke="#15803d" stroke-width="1.8" stroke-linecap="round"/>` +
    `</svg>`;
  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}

const BELL_PEPPER_ICON: Record<"red" | "yellow" | "green", string> = {
  red: pepperIcon("#e23b3b"),
  yellow: pepperIcon("#f2c037"),
  green: pepperIcon("#36b34a"),
};

export const FOOD_PRESETS: FoodPreset[] = [
  // Veg (per gram)
  {
    id: "bell-red",
    name: "Bell pepper (red)",
    emoji: "🫑",
    iconImageDataUrl: BELL_PEPPER_ICON.red,
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.31,
    proteinPer: 0.01,
    fiberPer: 0.021,
    carbsPer: 0.06,
    fatsPer: 0.003,
    category: "veg",
    source: "USDA FDC #170427 (red sweet pepper, raw)",
  },
  {
    id: "bell-green",
    name: "Bell pepper (green)",
    emoji: "🫑",
    iconImageDataUrl: BELL_PEPPER_ICON.green,
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.2,
    proteinPer: 0.0086,
    fiberPer: 0.017,
    carbsPer: 0.047,
    fatsPer: 0.0017,
    category: "veg",
    source: "USDA FDC #170427 (green sweet pepper, raw)",
  },
  {
    id: "bell-yellow",
    name: "Bell pepper (yellow)",
    emoji: "🫑",
    iconImageDataUrl: BELL_PEPPER_ICON.yellow,
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.27,
    proteinPer: 0.01,
    fiberPer: 0.009,
    carbsPer: 0.064,
    fatsPer: 0.0021,
    category: "veg",
    source: "USDA FDC #170427 (yellow sweet pepper, raw)",
  },
  {
    id: "cucumber",
    name: "Cucumber",
    emoji: "🥒",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.15,
    proteinPer: 0.0065,
    fiberPer: 0.005,
    carbsPer: 0.036,
    fatsPer: 0.0011,
    category: "veg",
    source: "USDA FDC #168409 (cucumber with peel, raw)",
  },
  {
    id: "tomato",
    name: "Tomato",
    emoji: "🍅",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.18,
    proteinPer: 0.0088,
    fiberPer: 0.012,
    carbsPer: 0.039,
    fatsPer: 0.002,
    category: "veg",
    source: "USDA FDC #170457 (tomato, raw)",
  },
  {
    id: "broccoli",
    name: "Broccoli",
    emoji: "🥦",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.34,
    proteinPer: 0.0282,
    fiberPer: 0.026,
    carbsPer: 0.0664,
    fatsPer: 0.0037,
    category: "veg",
    source: "USDA FDC #170379 (broccoli, raw)",
  },
  {
    id: "spinach",
    name: "Spinach",
    emoji: "🥬",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.23,
    proteinPer: 0.0286,
    fiberPer: 0.022,
    carbsPer: 0.0363,
    fatsPer: 0.0039,
    category: "veg",
    source: "USDA FDC #168462 (spinach, raw)",
  },
  {
    id: "salad-mixed",
    name: "Mixed salad",
    emoji: "🥗",
    unit: "g",
    defaultAmount: 150,
    caloriesPer: 0.2,
    proteinPer: 0.012,
    fiberPer: 0.018,
    carbsPer: 0.035,
    fatsPer: 0.003,
    category: "veg",
    source: "Generic estimate, mixed greens + veg blend",
  },
  {
    id: "mushroom",
    name: "Mushrooms (button)",
    emoji: "🍄",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.22,
    proteinPer: 0.031,
    fiberPer: 0.01,
    carbsPer: 0.033,
    fatsPer: 0.003,
    category: "veg",
    source: "USDA FDC #169251 (white mushrooms, raw)",
  },
  {
    id: "eggplant",
    name: "Eggplant",
    emoji: "🍆",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.25,
    proteinPer: 0.01,
    fiberPer: 0.03,
    carbsPer: 0.059,
    fatsPer: 0.002,
    category: "veg",
    source: "USDA FDC #169228 (eggplant, raw)",
  },
  {
    id: "onion-brown",
    name: "Brown onion",
    emoji: "🧅",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.4,
    proteinPer: 0.011,
    fiberPer: 0.017,
    carbsPer: 0.093,
    fatsPer: 0.001,
    category: "veg",
    source: "USDA FDC #170000 (onions, raw)",
  },
  {
    id: "onion-red",
    name: "Red onion",
    emoji: "🧅",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.42,
    proteinPer: 0.011,
    fiberPer: 0.017,
    carbsPer: 0.096,
    fatsPer: 0.001,
    category: "veg",
    source: "USDA FDC #170000 (red onion, raw)",
  },
  {
    id: "carrot",
    name: "Carrot",
    emoji: "🥕",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.41,
    proteinPer: 0.009,
    fiberPer: 0.028,
    carbsPer: 0.096,
    fatsPer: 0.002,
    category: "veg",
    source: "USDA FDC #170393 (carrots, raw)",
  },
  {
    id: "zucchini",
    name: "Zucchini",
    emoji: "🥒",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.17,
    proteinPer: 0.012,
    fiberPer: 0.01,
    carbsPer: 0.031,
    fatsPer: 0.003,
    category: "veg",
    source: "USDA FDC #169291 (zucchini/courgette, raw)",
  },
  {
    id: "pumpkin",
    name: "Pumpkin",
    emoji: "🎃",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.26,
    proteinPer: 0.01,
    fiberPer: 0.005,
    carbsPer: 0.065,
    fatsPer: 0.001,
    category: "veg",
    source: "USDA FDC #168448 (pumpkin, raw)",
  },
  {
    id: "peas-green",
    name: "Green peas",
    emoji: "🫛",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.81,
    proteinPer: 0.054,
    fiberPer: 0.057,
    carbsPer: 0.145,
    fatsPer: 0.004,
    category: "veg",
    source: "USDA FDC #170419 (green peas, raw)",
  },
  {
    id: "sweetcorn",
    name: "Sweetcorn",
    emoji: "🌽",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.86,
    proteinPer: 0.033,
    fiberPer: 0.02,
    carbsPer: 0.19,
    fatsPer: 0.014,
    category: "veg",
    source: "USDA FDC #169998 (sweet corn, raw)",
  },
  {
    id: "lettuce",
    name: "Lettuce",
    emoji: "🥬",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.15,
    proteinPer: 0.014,
    fiberPer: 0.013,
    carbsPer: 0.029,
    fatsPer: 0.002,
    category: "veg",
    source: "USDA FDC #169247 (cos/romaine lettuce, raw)",
  },
  {
    id: "garlic",
    name: "Garlic",
    emoji: "🧄",
    unit: "g",
    defaultAmount: 10,
    caloriesPer: 1.49,
    proteinPer: 0.064,
    fiberPer: 0.021,
    carbsPer: 0.331,
    fatsPer: 0.005,
    category: "veg",
    source: "USDA FDC #169230 (garlic, raw)",
  },
  {
    id: "radish-daikon",
    // No radish emoji exists in Unicode; 🥒 is the closest pale, elongated
    // root. Users can re-pick the icon from the food's edit screen.
    name: "White radish (daikon)",
    emoji: "🥒",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.18,
    proteinPer: 0.006,
    fiberPer: 0.016,
    carbsPer: 0.041,
    fatsPer: 0.001,
    category: "veg",
    source: "USDA FDC #169276 (radishes, oriental/daikon, raw)",
  },

  // Eggs (per gram — sizes vary too much to use pieces)
  {
    id: "egg-white",
    name: "Egg white",
    emoji: "🥚",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.52,
    proteinPer: 0.109,
    fiberPer: 0,
    carbsPer: 0.0073,
    fatsPer: 0.0017,
    category: "protein",
    source: "USDA FDC #748967 (egg white, raw, fresh)",
  },
  {
    id: "egg-yolk",
    name: "Egg yolk",
    emoji: "🍳",
    unit: "g",
    defaultAmount: 50,
    caloriesPer: 3.22,
    proteinPer: 0.1587,
    fiberPer: 0,
    carbsPer: 0.0364,
    fatsPer: 0.2654,
    category: "protein",
    source: "USDA FDC #172183 (egg yolk, raw, fresh)",
  },
  {
    id: "egg-whole",
    name: "Whole egg",
    emoji: "🥚",
    unit: "g",
    defaultAmount: 50,
    caloriesPer: 1.43,
    proteinPer: 0.1256,
    fiberPer: 0,
    carbsPer: 0.0072,
    fatsPer: 0.0951,
    category: "protein",
    source: "USDA FDC #748967 (whole egg, raw, fresh)",
  },

  // Fats (per gram)
  {
    id: "avocado",
    name: "Avocado",
    emoji: "🥑",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 1.6,
    proteinPer: 0.02,
    fiberPer: 0.067,
    carbsPer: 0.0853,
    fatsPer: 0.1466,
    category: "fat",
    source: "USDA FDC #171705 (avocado, raw, all varieties)",
  },
  {
    id: "almonds",
    name: "Almonds",
    emoji: "🌰",
    unit: "g",
    defaultAmount: 30,
    caloriesPer: 5.79,
    proteinPer: 0.2115,
    fiberPer: 0.125,
    carbsPer: 0.2161,
    fatsPer: 0.4993,
    category: "fat",
    source: "USDA FDC #170567 (almonds, raw)",
  },
  {
    id: "peanut-butter",
    name: "Peanut butter",
    emoji: "🥜",
    unit: "g",
    defaultAmount: 30,
    caloriesPer: 5.88,
    proteinPer: 0.2249,
    fiberPer: 0.06,
    carbsPer: 0.2189,
    fatsPer: 0.5036,
    category: "fat",
    source: "USDA FDC #172470 (peanut butter, smooth)",
  },
  {
    id: "olive-oil",
    name: "Olive oil",
    emoji: "🧴",
    unit: "ml",
    defaultAmount: 10,
    caloriesPer: 8.84,
    proteinPer: 0,
    fiberPer: 0,
    carbsPer: 0,
    fatsPer: 1,
    category: "fat",
    source: "USDA FDC #748608 (olive oil, ~0.92 g/ml density)",
  },

  // Fruits
  {
    id: "banana",
    name: "Banana (medium)",
    emoji: "🍌",
    unit: "piece",
    defaultAmount: 1,
    caloriesPer: 105,
    proteinPer: 1.3,
    fiberPer: 3.1,
    carbsPer: 27,
    fatsPer: 0.4,
    category: "fruit",
    source: "USDA FDC #173944 (banana, raw, medium ~118 g)",
  },
  {
    id: "apple",
    name: "Apple (medium)",
    emoji: "🍎",
    unit: "piece",
    defaultAmount: 1,
    caloriesPer: 95,
    proteinPer: 0.5,
    fiberPer: 4.4,
    carbsPer: 25,
    fatsPer: 0.3,
    category: "fruit",
    source: "USDA FDC #171688 (apple with skin, raw, medium ~182 g)",
  },
  {
    id: "orange",
    name: "Orange (medium)",
    emoji: "🍊",
    unit: "piece",
    defaultAmount: 1,
    caloriesPer: 62,
    proteinPer: 1.2,
    fiberPer: 3.1,
    carbsPer: 15,
    fatsPer: 0.2,
    category: "fruit",
    source: "USDA FDC #169097 (orange, raw, medium ~131 g)",
  },
  {
    id: "mango",
    name: "Mango",
    emoji: "🥭",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.6,
    proteinPer: 0.0082,
    fiberPer: 0.016,
    carbsPer: 0.1498,
    fatsPer: 0.0038,
    category: "fruit",
    source: "USDA FDC #169910 (mango, raw)",
  },
  {
    id: "watermelon",
    name: "Watermelon",
    emoji: "🍉",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.3,
    proteinPer: 0.0061,
    fiberPer: 0.004,
    carbsPer: 0.0755,
    fatsPer: 0.0015,
    category: "fruit",
    source: "USDA FDC #167765 (watermelon, raw)",
  },
  {
    id: "strawberry",
    name: "Strawberries",
    emoji: "🍓",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.32,
    proteinPer: 0.0067,
    fiberPer: 0.02,
    carbsPer: 0.0768,
    fatsPer: 0.003,
    category: "fruit",
    source: "USDA FDC #167762 (strawberries, raw)",
  },
  {
    id: "pineapple",
    name: "Pineapple",
    emoji: "🍍",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.5,
    proteinPer: 0.0054,
    fiberPer: 0.014,
    carbsPer: 0.131,
    fatsPer: 0.0012,
    category: "fruit",
    source: "USDA FDC #169124 (pineapple, raw)",
  },
  {
    id: "kiwi",
    name: "Kiwi (medium)",
    emoji: "🥝",
    unit: "piece",
    defaultAmount: 1,
    caloriesPer: 42,
    proteinPer: 0.8,
    fiberPer: 2.1,
    carbsPer: 10,
    fatsPer: 0.4,
    category: "fruit",
    source: "USDA FDC #168153 (kiwifruit, raw, medium ~69 g)",
  },
  {
    id: "pear",
    name: "Pear (medium)",
    emoji: "🍐",
    unit: "piece",
    defaultAmount: 1,
    caloriesPer: 101,
    proteinPer: 0.6,
    fiberPer: 5.5,
    carbsPer: 27,
    fatsPer: 0.2,
    category: "fruit",
    source: "USDA FDC #169118 (pear, raw, medium ~178 g)",
  },
  {
    id: "peach",
    name: "Peach (medium)",
    emoji: "🍑",
    unit: "piece",
    defaultAmount: 1,
    caloriesPer: 58,
    proteinPer: 1.4,
    fiberPer: 2.3,
    carbsPer: 14,
    fatsPer: 0.4,
    category: "fruit",
    source: "USDA FDC #169928 (peach, raw, medium ~150 g)",
  },
  {
    id: "mandarin",
    name: "Mandarin (medium)",
    emoji: "🍊",
    unit: "piece",
    defaultAmount: 1,
    caloriesPer: 47,
    proteinPer: 0.7,
    fiberPer: 1.6,
    carbsPer: 12,
    fatsPer: 0.3,
    category: "fruit",
    source: "USDA FDC #169105 (mandarin/tangerine, raw, medium ~88 g)",
  },
  {
    id: "grapes",
    name: "Grapes",
    emoji: "🍇",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.69,
    proteinPer: 0.007,
    fiberPer: 0.009,
    carbsPer: 0.18,
    fatsPer: 0.002,
    category: "fruit",
    source: "USDA FDC #174683 (grapes, red/green, raw)",
  },
  {
    id: "blueberries",
    name: "Blueberries",
    emoji: "🫐",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.57,
    proteinPer: 0.007,
    fiberPer: 0.024,
    carbsPer: 0.145,
    fatsPer: 0.003,
    category: "fruit",
    source: "USDA FDC #171711 (blueberries, raw)",
  },
  {
    id: "cherries",
    name: "Cherries",
    emoji: "🍒",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.63,
    proteinPer: 0.011,
    fiberPer: 0.021,
    carbsPer: 0.16,
    fatsPer: 0.002,
    category: "fruit",
    source: "USDA FDC #171719 (sweet cherries, raw)",
  },
  {
    id: "lemon",
    name: "Lemon",
    emoji: "🍋",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.29,
    proteinPer: 0.011,
    fiberPer: 0.028,
    carbsPer: 0.093,
    fatsPer: 0.003,
    category: "fruit",
    source: "USDA FDC #167746 (lemon, raw)",
  },
  {
    id: "rockmelon",
    name: "Rockmelon",
    emoji: "🍈",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.34,
    proteinPer: 0.008,
    fiberPer: 0.009,
    carbsPer: 0.082,
    fatsPer: 0.002,
    category: "fruit",
    source: "USDA FDC #169092 (cantaloupe/rockmelon, raw)",
  },

  // Protein
  {
    id: "chicken-breast",
    name: "Chicken breast (cooked)",
    emoji: "🍗",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 1.65,
    proteinPer: 0.31,
    fiberPer: 0,
    carbsPer: 0,
    fatsPer: 0.0357,
    category: "protein",
    source: "USDA FDC #171477 (chicken breast, roasted)",
  },
  {
    id: "fish-salmon",
    name: "Salmon (cooked)",
    emoji: "🐟",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 2.06,
    proteinPer: 0.2235,
    fiberPer: 0,
    carbsPer: 0,
    fatsPer: 0.1235,
    category: "protein",
    source: "USDA FDC #175168 (Atlantic salmon, cooked, dry heat)",
  },
  {
    id: "paneer",
    name: "Paneer",
    emoji: "🧀",
    unit: "g",
    defaultAmount: 50,
    caloriesPer: 2.96,
    proteinPer: 0.2486,
    fiberPer: 0,
    carbsPer: 0.062,
    fatsPer: 0.207,
    category: "dairy",
    source: "IFCT 2017 (paneer, full-fat cow milk)",
  },
  {
    id: "greek-yogurt",
    name: "Greek yogurt (non-fat)",
    emoji: "🥣",
    unit: "g",
    defaultAmount: 150,
    caloriesPer: 0.59,
    proteinPer: 0.1019,
    fiberPer: 0,
    carbsPer: 0.0364,
    fatsPer: 0.0039,
    category: "dairy",
    source: "USDA FDC #173304 (Greek yogurt, plain, non-fat)",
  },
  {
    id: "milk",
    name: "Milk (full cream)",
    emoji: "🥛",
    unit: "ml",
    defaultAmount: 200,
    caloriesPer: 0.61,
    proteinPer: 0.032,
    fiberPer: 0,
    carbsPer: 0.048,
    fatsPer: 0.0333,
    category: "dairy",
    source: "USDA FDC #171265 (whole milk, 3.25 % fat) · ~1.03 g/ml",
  },
  {
    id: "whey",
    name: "Whey protein scoop",
    emoji: "💪",
    unit: "piece",
    defaultAmount: 1,
    caloriesPer: 120,
    proteinPer: 24,
    fiberPer: 0.5,
    carbsPer: 3,
    fatsPer: 1.5,
    category: "protein",
    source: "Generic isolate/concentrate label (~30 g scoop)",
  },
  {
    id: "tofu",
    name: "Tofu (firm)",
    emoji: "🍥",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.76,
    proteinPer: 0.0808,
    fiberPer: 0.009,
    carbsPer: 0.0188,
    fatsPer: 0.0478,
    category: "protein",
    source: "USDA FDC #172476 (tofu, firm, prepared with calcium sulfate)",
  },

  // Carbs
  {
    id: "rice-cooked",
    name: "Rice (cooked, white)",
    emoji: "🍚",
    unit: "g",
    defaultAmount: 150,
    caloriesPer: 1.3,
    proteinPer: 0.0269,
    fiberPer: 0.004,
    carbsPer: 0.2817,
    fatsPer: 0.0028,
    category: "carb",
    source: "USDA FDC #169757 (rice, white, long-grain, cooked)",
  },
  {
    id: "oats-dry",
    name: "Oats (dry, rolled)",
    emoji: "🥣",
    unit: "g",
    defaultAmount: 40,
    caloriesPer: 3.79,
    proteinPer: 0.1369,
    fiberPer: 0.101,
    carbsPer: 0.6759,
    fatsPer: 0.0689,
    category: "carb",
    source: "USDA FDC #173904 (oats, raw)",
  },
  {
    id: "roti",
    name: "Roti / chapati (~40 g)",
    emoji: "🥙",
    unit: "piece",
    defaultAmount: 1,
    caloriesPer: 120,
    proteinPer: 3.5,
    fiberPer: 2.0,
    carbsPer: 18,
    fatsPer: 3.0,
    category: "carb",
    source:
      "IFCT 2017 + typical home recipe (whole wheat flour ~40 g + a tsp oil)",
  },
  {
    id: "bread",
    name: "Bread slice (whole wheat)",
    emoji: "🍞",
    unit: "piece",
    defaultAmount: 1,
    caloriesPer: 81,
    proteinPer: 4,
    fiberPer: 2,
    carbsPer: 13.8,
    fatsPer: 1.1,
    category: "carb",
    source: "USDA FDC #172684 (whole-wheat bread, commercial, ~30 g slice)",
  },
  {
    id: "sweet-potato",
    name: "Sweet potato (cooked)",
    emoji: "🍠",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.9,
    proteinPer: 0.02,
    fiberPer: 0.033,
    carbsPer: 0.207,
    fatsPer: 0.002,
    category: "carb",
    source: "USDA FDC #168483 (sweet potato, baked in skin)",
  },
  {
    id: "potato",
    name: "Potato (cooked)",
    emoji: "🥔",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.87,
    proteinPer: 0.019,
    fiberPer: 0.018,
    carbsPer: 0.201,
    fatsPer: 0.001,
    category: "carb",
    source: "USDA FDC #170032 (potato, boiled, flesh, no skin)",
  },

  // Dairy (per gram unless noted). Paneer / Greek yogurt / milk also live
  // here (their ids are unchanged for backwards-compat).
  {
    id: "curd-plain",
    name: "Curd / plain yogurt",
    emoji: "🥣",
    unit: "g",
    defaultAmount: 150,
    caloriesPer: 0.61,
    proteinPer: 0.035,
    fiberPer: 0,
    carbsPer: 0.047,
    fatsPer: 0.0333,
    category: "dairy",
    source: "USDA FDC #170886 (whole-milk plain yogurt / dahi)",
  },
  {
    id: "cottage-cheese",
    name: "Cottage cheese (low-fat)",
    emoji: "🧀",
    unit: "g",
    defaultAmount: 100,
    caloriesPer: 0.84,
    proteinPer: 0.11,
    fiberPer: 0,
    carbsPer: 0.0455,
    fatsPer: 0.0243,
    category: "dairy",
    source: "USDA FDC #173417 (cottage cheese, lowfat, 2% milkfat)",
  },
  {
    id: "cheese-cheddar",
    name: "Cheese (cheddar)",
    emoji: "🧀",
    unit: "g",
    defaultAmount: 30,
    caloriesPer: 4.03,
    proteinPer: 0.2249,
    fiberPer: 0,
    carbsPer: 0.0331,
    fatsPer: 0.3314,
    category: "dairy",
    source: "USDA FDC #173410 (cheddar cheese)",
  },

  // Sauces / condiments. Easy to forget and surprisingly calorie-dense, so
  // small default amounts (≈ a tbsp/tsp) keep logging realistic.
  {
    id: "sauce-ketchup",
    name: "Ketchup",
    emoji: "🍅",
    unit: "g",
    defaultAmount: 15,
    caloriesPer: 1.01,
    proteinPer: 0.0118,
    fiberPer: 0.003,
    carbsPer: 0.2629,
    fatsPer: 0.001,
    category: "sauce",
    source: "USDA FDC #168556 (ketchup)",
  },
  {
    id: "sauce-mayo",
    name: "Mayonnaise",
    emoji: "🥫",
    unit: "g",
    defaultAmount: 15,
    caloriesPer: 6.8,
    proteinPer: 0.01,
    fiberPer: 0,
    carbsPer: 0.006,
    fatsPer: 0.75,
    category: "sauce",
    source: "USDA FDC #343039 (mayonnaise, regular)",
  },
  {
    id: "sauce-mayo-light",
    name: "Light mayo",
    emoji: "🥫",
    unit: "g",
    defaultAmount: 15,
    caloriesPer: 3.3,
    proteinPer: 0.008,
    fiberPer: 0,
    carbsPer: 0.09,
    fatsPer: 0.33,
    category: "sauce",
    source: "USDA FDC #2706393 (mayonnaise, light / reduced fat)",
  },
  {
    id: "sauce-hot",
    name: "Hot sauce",
    emoji: "🌶️",
    unit: "g",
    defaultAmount: 10,
    caloriesPer: 0.6,
    proteinPer: 0.005,
    fiberPer: 0.003,
    carbsPer: 0.12,
    fatsPer: 0.004,
    category: "sauce",
    source: "Generic chilli/sriracha-style hot sauce estimate",
  },
  {
    id: "sauce-soy",
    name: "Soy sauce",
    emoji: "🥫",
    unit: "ml",
    defaultAmount: 15,
    caloriesPer: 0.53,
    proteinPer: 0.08,
    fiberPer: 0.008,
    carbsPer: 0.049,
    fatsPer: 0.0006,
    category: "sauce",
    source: "USDA FDC #174277 (soy sauce, ~1.15 g/ml)",
  },
  {
    id: "sauce-bbq",
    name: "BBQ sauce",
    emoji: "🍯",
    unit: "g",
    defaultAmount: 30,
    caloriesPer: 1.72,
    proteinPer: 0.008,
    fiberPer: 0.007,
    carbsPer: 0.408,
    fatsPer: 0.0063,
    category: "sauce",
    source: "USDA FDC #170884 (barbecue sauce)",
  },
  {
    id: "sauce-hummus",
    name: "Hummus",
    emoji: "🥣",
    unit: "g",
    defaultAmount: 30,
    caloriesPer: 1.66,
    proteinPer: 0.0758,
    fiberPer: 0.06,
    carbsPer: 0.1431,
    fatsPer: 0.0986,
    category: "sauce",
    source: "USDA FDC #173735 (hummus, commercial)",
  },
  {
    id: "sauce-chutney",
    name: "Chutney (sweet)",
    emoji: "🥭",
    unit: "g",
    defaultAmount: 20,
    caloriesPer: 2.4,
    proteinPer: 0.005,
    fiberPer: 0.011,
    carbsPer: 0.585,
    fatsPer: 0.002,
    category: "sauce",
    source: "Typical mango / sweet chutney label estimate",
  },
  {
    id: "sauce-salsa",
    name: "Salsa",
    emoji: "🍅",
    unit: "g",
    defaultAmount: 30,
    caloriesPer: 0.36,
    proteinPer: 0.0152,
    fiberPer: 0.0152,
    carbsPer: 0.0758,
    fatsPer: 0.0015,
    category: "sauce",
    source: "USDA FDC #1102718 (salsa, ready-to-serve)",
  },
  {
    id: "sauce-mustard",
    name: "Mustard",
    emoji: "🌭",
    unit: "g",
    defaultAmount: 10,
    caloriesPer: 0.66,
    proteinPer: 0.0374,
    fiberPer: 0.04,
    carbsPer: 0.058,
    fatsPer: 0.0341,
    category: "sauce",
    source: "USDA FDC #168577 (mustard, prepared, yellow)",
  },
  {
    id: "sauce-periperi",
    name: "Peri-peri sauce",
    emoji: "🌶️",
    unit: "g",
    defaultAmount: 15,
    caloriesPer: 0.9,
    proteinPer: 0.01,
    fiberPer: 0.005,
    carbsPer: 0.08,
    fatsPer: 0.06,
    category: "sauce",
    source: "Typical peri-peri / hot garlic sauce label estimate",
  },
  {
    id: "sauce-sweet-chilli",
    name: "Sweet chilli sauce",
    emoji: "🌶️",
    unit: "g",
    defaultAmount: 15,
    caloriesPer: 2.25,
    proteinPer: 0.006,
    fiberPer: 0.004,
    carbsPer: 0.55,
    fatsPer: 0.002,
    category: "sauce",
    source: "Typical sweet chilli dipping sauce label estimate",
  },

  // Drinks (no category target — these live under My foods via search)
];

export const UNIT_LABEL: Record<FoodUnit, string> = {
  g: "g",
  ml: "ml",
  piece: "pc",
};

export type MacroSource = {
  caloriesPer: number;
  proteinPer: number;
  fiberPer?: number;
  carbsPer?: number;
  fatsPer?: number;
};

export type Macros = {
  calories: number;
  protein: number;
  fiber: number;
  carbs: number;
  fats: number;
};

export function calcMacros(food: MacroSource, amount: number): Macros {
  return {
    calories: Math.round(food.caloriesPer * amount),
    protein: Math.round(food.proteinPer * amount * 10) / 10,
    fiber: Math.round((food.fiberPer ?? 0) * amount * 10) / 10,
    carbs: Math.round((food.carbsPer ?? 0) * amount * 10) / 10,
    fats: Math.round((food.fatsPer ?? 0) * amount * 10) / 10,
  };
}
